// GENERATED by scripts/generate-docs.mjs from scripts/docs-manifest.mjs's `hub` field — do not hand-edit.
// Breadcrumb trail for pages hidden from nav.js (see that file's own comment).
module.exports = {
  "/reference/api/authentication/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ]
  },
  "/reference/api/design/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ]
  },
  "/reference/api/build/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ]
  },
  "/reference/api/deploy/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ]
  },
  "/reference/api/operate/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ]
  },
  "/reference/api/management-operations/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ]
  },
  "/reference/architecture-reference/connection-and-handshake/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ]
  },
  "/reference/architecture-reference/channels/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ]
  },
  "/reference/architecture-reference/conversation-flow/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ]
  },
  "/reference/architecture-reference/scale-and-sticky-sessions/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ]
  },
  "/reference/architecture-reference/module-map-and-data-flow/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ]
  },
  "/reference/architecture-reference/resilience-and-failure-handling/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ]
  },
  "/reference/wire-protocol/connection-basics/": {
    "trail": [
      {
        "title": "Wire Protocol",
        "url": "/reference/wire-protocol/"
      }
    ]
  },
  "/reference/wire-protocol/events-catalog/": {
    "trail": [
      {
        "title": "Wire Protocol",
        "url": "/reference/wire-protocol/"
      }
    ]
  },
  "/reference/wire-protocol/audio-channels/": {
    "trail": [
      {
        "title": "Wire Protocol",
        "url": "/reference/wire-protocol/"
      }
    ]
  },
  "/reference/wire-protocol/client-configuration/": {
    "trail": [
      {
        "title": "Wire Protocol",
        "url": "/reference/wire-protocol/"
      }
    ]
  },
  "/reference/wire-protocol/end-to-end-turn/": {
    "trail": [
      {
        "title": "Wire Protocol",
        "url": "/reference/wire-protocol/"
      }
    ]
  },
  "/reference/genui/model-and-runtimes/": {
    "trail": [
      {
        "title": "GenUI Reference",
        "url": "/reference/genui-reference/"
      }
    ]
  },
  "/reference/genui/widgets/": {
    "trail": [
      {
        "title": "GenUI Reference",
        "url": "/reference/genui-reference/"
      }
    ]
  },
  "/reference/genui/authoring-and-consuming/": {
    "trail": [
      {
        "title": "GenUI Reference",
        "url": "/reference/genui-reference/"
      }
    ]
  },
  "/reference/genui/analytics/": {
    "trail": [
      {
        "title": "GenUI Reference",
        "url": "/reference/genui-reference/"
      }
    ]
  },
  "/reference/genui/safety-and-restrictions/": {
    "trail": [
      {
        "title": "GenUI Reference",
        "url": "/reference/genui-reference/"
      }
    ]
  },
  "/reference/api/build/intellect/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      }
    ]
  },
  "/reference/api/build/preview-prompt/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      }
    ]
  },
  "/reference/api/build/tools-and-secrets/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      }
    ]
  },
  "/reference/api/build/knowledge-rag/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      }
    ]
  },
  "/reference/api/build/avatar-and-agent/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      }
    ]
  }
};
