// GENERATED by scripts/generate-docs.mjs from scripts/docs-manifest.mjs's `hub` field — do not hand-edit.
// Breadcrumb trail + sibling links for pages hidden from nav.js (see that file's own comment).
module.exports = {
  "/reference/api/authentication/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Catalog & Assets",
        "url": "/reference/api/design/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      },
      {
        "title": "Widget & Runtime Init",
        "url": "/reference/api/deploy/"
      },
      {
        "title": "Conversation & Analytics",
        "url": "/reference/api/operate/"
      },
      {
        "title": "Management Operations",
        "url": "/reference/api/management-operations/"
      }
    ]
  },
  "/reference/api/design/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Authentication & Services",
        "url": "/reference/api/authentication/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      },
      {
        "title": "Widget & Runtime Init",
        "url": "/reference/api/deploy/"
      },
      {
        "title": "Conversation & Analytics",
        "url": "/reference/api/operate/"
      },
      {
        "title": "Management Operations",
        "url": "/reference/api/management-operations/"
      }
    ]
  },
  "/reference/api/build/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Authentication & Services",
        "url": "/reference/api/authentication/"
      },
      {
        "title": "Catalog & Assets",
        "url": "/reference/api/design/"
      },
      {
        "title": "Widget & Runtime Init",
        "url": "/reference/api/deploy/"
      },
      {
        "title": "Conversation & Analytics",
        "url": "/reference/api/operate/"
      },
      {
        "title": "Management Operations",
        "url": "/reference/api/management-operations/"
      }
    ]
  },
  "/reference/api/deploy/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Authentication & Services",
        "url": "/reference/api/authentication/"
      },
      {
        "title": "Catalog & Assets",
        "url": "/reference/api/design/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      },
      {
        "title": "Conversation & Analytics",
        "url": "/reference/api/operate/"
      },
      {
        "title": "Management Operations",
        "url": "/reference/api/management-operations/"
      }
    ]
  },
  "/reference/api/operate/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Authentication & Services",
        "url": "/reference/api/authentication/"
      },
      {
        "title": "Catalog & Assets",
        "url": "/reference/api/design/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      },
      {
        "title": "Widget & Runtime Init",
        "url": "/reference/api/deploy/"
      },
      {
        "title": "Management Operations",
        "url": "/reference/api/management-operations/"
      }
    ]
  },
  "/reference/api/management-operations/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Authentication & Services",
        "url": "/reference/api/authentication/"
      },
      {
        "title": "Catalog & Assets",
        "url": "/reference/api/design/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      },
      {
        "title": "Widget & Runtime Init",
        "url": "/reference/api/deploy/"
      },
      {
        "title": "Conversation & Analytics",
        "url": "/reference/api/operate/"
      }
    ]
  },
  "/reference/architecture-reference/connection-and-handshake/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Audio & Video Wiring",
        "url": "/reference/architecture-reference/channels/"
      },
      {
        "title": "Conversation Flow",
        "url": "/reference/architecture-reference/conversation-flow/"
      },
      {
        "title": "Scale and Sticky Sessions",
        "url": "/reference/architecture-reference/scale-and-sticky-sessions/"
      },
      {
        "title": "Module Map and Data Flow",
        "url": "/reference/architecture-reference/module-map-and-data-flow/"
      },
      {
        "title": "Resilience and Failure Handling",
        "url": "/reference/architecture-reference/resilience-and-failure-handling/"
      }
    ]
  },
  "/reference/architecture-reference/channels/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Connection and Handshake",
        "url": "/reference/architecture-reference/connection-and-handshake/"
      },
      {
        "title": "Conversation Flow",
        "url": "/reference/architecture-reference/conversation-flow/"
      },
      {
        "title": "Scale and Sticky Sessions",
        "url": "/reference/architecture-reference/scale-and-sticky-sessions/"
      },
      {
        "title": "Module Map and Data Flow",
        "url": "/reference/architecture-reference/module-map-and-data-flow/"
      },
      {
        "title": "Resilience and Failure Handling",
        "url": "/reference/architecture-reference/resilience-and-failure-handling/"
      }
    ]
  },
  "/reference/architecture-reference/conversation-flow/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Connection and Handshake",
        "url": "/reference/architecture-reference/connection-and-handshake/"
      },
      {
        "title": "Audio & Video Wiring",
        "url": "/reference/architecture-reference/channels/"
      },
      {
        "title": "Scale and Sticky Sessions",
        "url": "/reference/architecture-reference/scale-and-sticky-sessions/"
      },
      {
        "title": "Module Map and Data Flow",
        "url": "/reference/architecture-reference/module-map-and-data-flow/"
      },
      {
        "title": "Resilience and Failure Handling",
        "url": "/reference/architecture-reference/resilience-and-failure-handling/"
      }
    ]
  },
  "/reference/architecture-reference/scale-and-sticky-sessions/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Connection and Handshake",
        "url": "/reference/architecture-reference/connection-and-handshake/"
      },
      {
        "title": "Audio & Video Wiring",
        "url": "/reference/architecture-reference/channels/"
      },
      {
        "title": "Conversation Flow",
        "url": "/reference/architecture-reference/conversation-flow/"
      },
      {
        "title": "Module Map and Data Flow",
        "url": "/reference/architecture-reference/module-map-and-data-flow/"
      },
      {
        "title": "Resilience and Failure Handling",
        "url": "/reference/architecture-reference/resilience-and-failure-handling/"
      }
    ]
  },
  "/reference/architecture-reference/module-map-and-data-flow/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Connection and Handshake",
        "url": "/reference/architecture-reference/connection-and-handshake/"
      },
      {
        "title": "Audio & Video Wiring",
        "url": "/reference/architecture-reference/channels/"
      },
      {
        "title": "Conversation Flow",
        "url": "/reference/architecture-reference/conversation-flow/"
      },
      {
        "title": "Scale and Sticky Sessions",
        "url": "/reference/architecture-reference/scale-and-sticky-sessions/"
      },
      {
        "title": "Resilience and Failure Handling",
        "url": "/reference/architecture-reference/resilience-and-failure-handling/"
      }
    ]
  },
  "/reference/architecture-reference/resilience-and-failure-handling/": {
    "trail": [
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Connection and Handshake",
        "url": "/reference/architecture-reference/connection-and-handshake/"
      },
      {
        "title": "Audio & Video Wiring",
        "url": "/reference/architecture-reference/channels/"
      },
      {
        "title": "Conversation Flow",
        "url": "/reference/architecture-reference/conversation-flow/"
      },
      {
        "title": "Scale and Sticky Sessions",
        "url": "/reference/architecture-reference/scale-and-sticky-sessions/"
      },
      {
        "title": "Module Map and Data Flow",
        "url": "/reference/architecture-reference/module-map-and-data-flow/"
      }
    ]
  },
  "/reference/wire-protocol/connection-basics/": {
    "trail": [
      {
        "title": "Wire Protocol",
        "url": "/reference/wire-protocol/"
      }
    ],
    "siblings": [
      {
        "title": "Events Catalog",
        "url": "/reference/wire-protocol/events-catalog/"
      },
      {
        "title": "Audio Channels",
        "url": "/reference/wire-protocol/audio-channels/"
      },
      {
        "title": "Client Configuration",
        "url": "/reference/wire-protocol/client-configuration/"
      },
      {
        "title": "End-to-End Turn",
        "url": "/reference/wire-protocol/end-to-end-turn/"
      }
    ]
  },
  "/reference/wire-protocol/events-catalog/": {
    "trail": [
      {
        "title": "Wire Protocol",
        "url": "/reference/wire-protocol/"
      }
    ],
    "siblings": [
      {
        "title": "Connection Basics",
        "url": "/reference/wire-protocol/connection-basics/"
      },
      {
        "title": "Audio Channels",
        "url": "/reference/wire-protocol/audio-channels/"
      },
      {
        "title": "Client Configuration",
        "url": "/reference/wire-protocol/client-configuration/"
      },
      {
        "title": "End-to-End Turn",
        "url": "/reference/wire-protocol/end-to-end-turn/"
      }
    ]
  },
  "/reference/wire-protocol/audio-channels/": {
    "trail": [
      {
        "title": "Wire Protocol",
        "url": "/reference/wire-protocol/"
      }
    ],
    "siblings": [
      {
        "title": "Connection Basics",
        "url": "/reference/wire-protocol/connection-basics/"
      },
      {
        "title": "Events Catalog",
        "url": "/reference/wire-protocol/events-catalog/"
      },
      {
        "title": "Client Configuration",
        "url": "/reference/wire-protocol/client-configuration/"
      },
      {
        "title": "End-to-End Turn",
        "url": "/reference/wire-protocol/end-to-end-turn/"
      }
    ]
  },
  "/reference/wire-protocol/client-configuration/": {
    "trail": [
      {
        "title": "Wire Protocol",
        "url": "/reference/wire-protocol/"
      }
    ],
    "siblings": [
      {
        "title": "Connection Basics",
        "url": "/reference/wire-protocol/connection-basics/"
      },
      {
        "title": "Events Catalog",
        "url": "/reference/wire-protocol/events-catalog/"
      },
      {
        "title": "Audio Channels",
        "url": "/reference/wire-protocol/audio-channels/"
      },
      {
        "title": "End-to-End Turn",
        "url": "/reference/wire-protocol/end-to-end-turn/"
      }
    ]
  },
  "/reference/wire-protocol/end-to-end-turn/": {
    "trail": [
      {
        "title": "Wire Protocol",
        "url": "/reference/wire-protocol/"
      }
    ],
    "siblings": [
      {
        "title": "Connection Basics",
        "url": "/reference/wire-protocol/connection-basics/"
      },
      {
        "title": "Events Catalog",
        "url": "/reference/wire-protocol/events-catalog/"
      },
      {
        "title": "Audio Channels",
        "url": "/reference/wire-protocol/audio-channels/"
      },
      {
        "title": "Client Configuration",
        "url": "/reference/wire-protocol/client-configuration/"
      }
    ]
  },
  "/reference/genui/model-and-runtimes/": {
    "trail": [
      {
        "title": "GenUI Reference",
        "url": "/reference/genui-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Per-Runtime Widget Detail",
        "url": "/reference/genui/widgets/"
      },
      {
        "title": "Authoring and Consuming Widgets",
        "url": "/reference/genui/authoring-and-consuming/"
      },
      {
        "title": "Widget Analytics",
        "url": "/reference/genui/analytics/"
      },
      {
        "title": "Safety and Restrictions",
        "url": "/reference/genui/safety-and-restrictions/"
      }
    ]
  },
  "/reference/genui/widgets/": {
    "trail": [
      {
        "title": "GenUI Reference",
        "url": "/reference/genui-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Model and Runtimes",
        "url": "/reference/genui/model-and-runtimes/"
      },
      {
        "title": "Authoring and Consuming Widgets",
        "url": "/reference/genui/authoring-and-consuming/"
      },
      {
        "title": "Widget Analytics",
        "url": "/reference/genui/analytics/"
      },
      {
        "title": "Safety and Restrictions",
        "url": "/reference/genui/safety-and-restrictions/"
      }
    ]
  },
  "/reference/genui/authoring-and-consuming/": {
    "trail": [
      {
        "title": "GenUI Reference",
        "url": "/reference/genui-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Model and Runtimes",
        "url": "/reference/genui/model-and-runtimes/"
      },
      {
        "title": "Per-Runtime Widget Detail",
        "url": "/reference/genui/widgets/"
      },
      {
        "title": "Widget Analytics",
        "url": "/reference/genui/analytics/"
      },
      {
        "title": "Safety and Restrictions",
        "url": "/reference/genui/safety-and-restrictions/"
      }
    ]
  },
  "/reference/genui/analytics/": {
    "trail": [
      {
        "title": "GenUI Reference",
        "url": "/reference/genui-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Model and Runtimes",
        "url": "/reference/genui/model-and-runtimes/"
      },
      {
        "title": "Per-Runtime Widget Detail",
        "url": "/reference/genui/widgets/"
      },
      {
        "title": "Authoring and Consuming Widgets",
        "url": "/reference/genui/authoring-and-consuming/"
      },
      {
        "title": "Safety and Restrictions",
        "url": "/reference/genui/safety-and-restrictions/"
      }
    ]
  },
  "/reference/genui/safety-and-restrictions/": {
    "trail": [
      {
        "title": "GenUI Reference",
        "url": "/reference/genui-reference/"
      }
    ],
    "siblings": [
      {
        "title": "Model and Runtimes",
        "url": "/reference/genui/model-and-runtimes/"
      },
      {
        "title": "Per-Runtime Widget Detail",
        "url": "/reference/genui/widgets/"
      },
      {
        "title": "Authoring and Consuming Widgets",
        "url": "/reference/genui/authoring-and-consuming/"
      },
      {
        "title": "Widget Analytics",
        "url": "/reference/genui/analytics/"
      }
    ]
  },
  "/reference/api/build/intellect/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      }
    ],
    "siblings": [
      {
        "title": "Preview a Prompt",
        "url": "/reference/api/build/preview-prompt/"
      },
      {
        "title": "Tools and Secrets",
        "url": "/reference/api/build/tools-and-secrets/"
      },
      {
        "title": "Ground the Agent in Your Content (RAG)",
        "url": "/reference/api/build/knowledge-rag/"
      },
      {
        "title": "Create an Avatar and an Agent",
        "url": "/reference/api/build/avatar-and-agent/"
      }
    ]
  },
  "/reference/api/build/preview-prompt/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      }
    ],
    "siblings": [
      {
        "title": "Create and Configure an Intellect",
        "url": "/reference/api/build/intellect/"
      },
      {
        "title": "Tools and Secrets",
        "url": "/reference/api/build/tools-and-secrets/"
      },
      {
        "title": "Ground the Agent in Your Content (RAG)",
        "url": "/reference/api/build/knowledge-rag/"
      },
      {
        "title": "Create an Avatar and an Agent",
        "url": "/reference/api/build/avatar-and-agent/"
      }
    ]
  },
  "/reference/api/build/tools-and-secrets/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      }
    ],
    "siblings": [
      {
        "title": "Create and Configure an Intellect",
        "url": "/reference/api/build/intellect/"
      },
      {
        "title": "Preview a Prompt",
        "url": "/reference/api/build/preview-prompt/"
      },
      {
        "title": "Ground the Agent in Your Content (RAG)",
        "url": "/reference/api/build/knowledge-rag/"
      },
      {
        "title": "Create an Avatar and an Agent",
        "url": "/reference/api/build/avatar-and-agent/"
      }
    ]
  },
  "/reference/api/build/knowledge-rag/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      }
    ],
    "siblings": [
      {
        "title": "Create and Configure an Intellect",
        "url": "/reference/api/build/intellect/"
      },
      {
        "title": "Preview a Prompt",
        "url": "/reference/api/build/preview-prompt/"
      },
      {
        "title": "Tools and Secrets",
        "url": "/reference/api/build/tools-and-secrets/"
      },
      {
        "title": "Create an Avatar and an Agent",
        "url": "/reference/api/build/avatar-and-agent/"
      }
    ]
  },
  "/reference/api/build/avatar-and-agent/": {
    "trail": [
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/"
      },
      {
        "title": "Agent Components",
        "url": "/reference/api/build/"
      }
    ],
    "siblings": [
      {
        "title": "Create and Configure an Intellect",
        "url": "/reference/api/build/intellect/"
      },
      {
        "title": "Preview a Prompt",
        "url": "/reference/api/build/preview-prompt/"
      },
      {
        "title": "Tools and Secrets",
        "url": "/reference/api/build/tools-and-secrets/"
      },
      {
        "title": "Ground the Agent in Your Content (RAG)",
        "url": "/reference/api/build/knowledge-rag/"
      }
    ]
  }
};
