// GENERATED by scripts/generate-docs.mjs from scripts/docs-manifest.mjs — do not hand-edit.
// Sidebar nav, grouped by Diátaxis quadrant (Tutorial → How-to Guides →
// Explanation → Reference — Diátaxis's own recommended reading order).
// Stays flat on purpose: split reference sub-pages are reached via their
// hub page's own link table, not flattened into the sidebar.
module.exports = [
  {
    group: 'Tutorial',
    pages: [
      { title: "Getting Started", url: "/getting-started/" },
    ],
  },
  {
    group: 'How-to Guides',
    pages: [
      { title: "Client-Side Commands", url: "/guides/client-commands/" },
      { title: "Site Navigation (go_to)", url: "/guides/site-navigation/" },
      { title: "Pause/Resume for Video", url: "/guides/pause-resume/" },
      { title: "Dynamic Data Injection", url: "/guides/dynamic-data-injection/" },
      { title: "Voice Input Modes", url: "/guides/voice-input-modes/" },
      { title: "Structured Data Forms", url: "/guides/structured-data-forms/" },
      { title: "External API Integrations", url: "/guides/external-api-integrations/" },
      { title: "Lifecycle Recipes", url: "/guides/lifecycle-recipes/" },
    ],
  },
  {
    group: 'Explanation',
    pages: [
      { title: "Platform Overview", url: "/explanation/architecture/" },
      { title: "Inside a Live Conversation", url: "/explanation/inside-a-live-conversation/" },
      { title: "Case Study: Nova", url: "/explanation/case-study-nova/" },
    ],
  },
  {
    group: 'Reference',
    pages: [
      { title: "SDK Reference", url: "/reference/sdk-reference/" },
      { title: "Backend API Reference", url: "/reference/api-reference/" },
      { title: "Lifecycle Rules", url: "/reference/lifecycle/" },
      { title: "Minimal Reimplementation Recipe", url: "/reference/architecture-recipe/" },
      { title: "System Internals Reference", url: "/reference/architecture-reference/" },
      { title: "Wire Protocol", url: "/reference/wire-protocol/" },
      { title: "GenUI Reference", url: "/reference/genui-reference/" },
      { title: "Use-Case Catalog", url: "/reference/use-cases/" },
      { title: "Security & Compliance", url: "/reference/security/" },
    ],
  },
];
