// GENERATED by scripts/generate-docs.mjs from scripts/docs-manifest.mjs — do not hand-edit.
// Sidebar nav, grouped by Diátaxis quadrant (Tutorial → How-to Guides →
// Explanation → Reference — Diátaxis's own recommended reading order).
// Each page nests its hidden `hub`-children (see docs-manifest.mjs) so a
// split reference topic's sub-pages stay reachable from the sidebar tree
// itself, not only via the hub page's own link table.
module.exports = [
  {
    "group": "Tutorial",
    "pages": [
      {
        "title": "Getting Started",
        "url": "/getting-started/",
        "children": []
      }
    ]
  },
  {
    "group": "How-to Guides",
    "pages": [
      {
        "title": "Client-Side Commands",
        "url": "/guides/client-commands/",
        "children": []
      },
      {
        "title": "Site Navigation (go_to)",
        "url": "/guides/site-navigation/",
        "children": []
      },
      {
        "title": "Pause/Resume for Video",
        "url": "/guides/pause-resume/",
        "children": []
      },
      {
        "title": "Dynamic Data Injection",
        "url": "/guides/dynamic-data-injection/",
        "children": []
      },
      {
        "title": "Voice Input Modes",
        "url": "/guides/voice-input-modes/",
        "children": []
      },
      {
        "title": "Structured Data Forms",
        "url": "/guides/structured-data-forms/",
        "children": []
      },
      {
        "title": "External API Integrations",
        "url": "/guides/external-api-integrations/",
        "children": []
      },
      {
        "title": "Lifecycle Recipes",
        "url": "/guides/lifecycle-recipes/",
        "children": []
      }
    ]
  },
  {
    "group": "Explanation",
    "pages": [
      {
        "title": "Platform Overview",
        "url": "/explanation/architecture/",
        "children": []
      },
      {
        "title": "Inside a Live Conversation",
        "url": "/explanation/inside-a-live-conversation/",
        "children": []
      },
      {
        "title": "Case Study: Nova",
        "url": "/explanation/case-study-nova/",
        "children": []
      }
    ]
  },
  {
    "group": "Reference",
    "pages": [
      {
        "title": "SDK Reference",
        "url": "/reference/sdk-reference/",
        "children": []
      },
      {
        "title": "Backend API Reference",
        "url": "/reference/api-reference/",
        "children": [
          {
            "title": "Authentication & Services",
            "url": "/reference/api/authentication/",
            "children": []
          },
          {
            "title": "Catalog & Assets",
            "url": "/reference/api/design/",
            "children": []
          },
          {
            "title": "Agent Components",
            "url": "/reference/api/build/",
            "children": [
              {
                "title": "Create and Configure an Intellect",
                "url": "/reference/api/build/intellect/",
                "children": []
              },
              {
                "title": "Preview a Prompt",
                "url": "/reference/api/build/preview-prompt/",
                "children": []
              },
              {
                "title": "Tools and Secrets",
                "url": "/reference/api/build/tools-and-secrets/",
                "children": []
              },
              {
                "title": "Ground the Agent in Your Content (RAG)",
                "url": "/reference/api/build/knowledge-rag/",
                "children": []
              },
              {
                "title": "Create an Avatar and an Agent",
                "url": "/reference/api/build/avatar-and-agent/",
                "children": []
              }
            ]
          },
          {
            "title": "Widget & Runtime Init",
            "url": "/reference/api/deploy/",
            "children": []
          },
          {
            "title": "Conversation & Analytics",
            "url": "/reference/api/operate/",
            "children": []
          },
          {
            "title": "Management Operations",
            "url": "/reference/api/management-operations/",
            "children": []
          }
        ]
      },
      {
        "title": "Lifecycle Rules",
        "url": "/reference/lifecycle/",
        "children": []
      },
      {
        "title": "Minimal Reimplementation Recipe",
        "url": "/reference/architecture-recipe/",
        "children": []
      },
      {
        "title": "System Internals Reference",
        "url": "/reference/architecture-reference/",
        "children": [
          {
            "title": "Connection and Handshake",
            "url": "/reference/architecture-reference/connection-and-handshake/",
            "children": []
          },
          {
            "title": "Audio & Video Wiring",
            "url": "/reference/architecture-reference/channels/",
            "children": []
          },
          {
            "title": "Conversation Flow",
            "url": "/reference/architecture-reference/conversation-flow/",
            "children": []
          },
          {
            "title": "Scale and Sticky Sessions",
            "url": "/reference/architecture-reference/scale-and-sticky-sessions/",
            "children": []
          },
          {
            "title": "Module Map and Data Flow",
            "url": "/reference/architecture-reference/module-map-and-data-flow/",
            "children": []
          },
          {
            "title": "Resilience and Failure Handling",
            "url": "/reference/architecture-reference/resilience-and-failure-handling/",
            "children": []
          }
        ]
      },
      {
        "title": "Wire Protocol",
        "url": "/reference/wire-protocol/",
        "children": [
          {
            "title": "Connection Basics",
            "url": "/reference/wire-protocol/connection-basics/",
            "children": []
          },
          {
            "title": "Events Catalog",
            "url": "/reference/wire-protocol/events-catalog/",
            "children": []
          },
          {
            "title": "Audio Channels",
            "url": "/reference/wire-protocol/audio-channels/",
            "children": []
          },
          {
            "title": "Client Configuration",
            "url": "/reference/wire-protocol/client-configuration/",
            "children": []
          },
          {
            "title": "End-to-End Turn",
            "url": "/reference/wire-protocol/end-to-end-turn/",
            "children": []
          }
        ]
      },
      {
        "title": "GenUI Reference",
        "url": "/reference/genui-reference/",
        "children": [
          {
            "title": "Model and Runtimes",
            "url": "/reference/genui/model-and-runtimes/",
            "children": []
          },
          {
            "title": "Per-Runtime Widget Detail",
            "url": "/reference/genui/widgets/",
            "children": []
          },
          {
            "title": "Authoring and Consuming Widgets",
            "url": "/reference/genui/authoring-and-consuming/",
            "children": []
          },
          {
            "title": "Widget Analytics",
            "url": "/reference/genui/analytics/",
            "children": []
          },
          {
            "title": "Safety and Restrictions",
            "url": "/reference/genui/safety-and-restrictions/",
            "children": []
          }
        ]
      },
      {
        "title": "Use-Case Catalog",
        "url": "/reference/use-cases/",
        "children": []
      },
      {
        "title": "Security & Compliance",
        "url": "/reference/security/",
        "children": []
      }
    ]
  }
];
